const projects=[
{title:'Best of de React',client:'Huto',cat:'montage',label:'MONTAGE • BEST OF',desc:'Best of de react construit à partir du live, avec un montage centré sur le rythme et les meilleurs moments.',role:'Dérush, musique, léger FX et zoom',challenge:'Condense le contenu du live pour ne garder que les passages les plus efficaces, sans casser le naturel des réactions.',production:'Sélection des moments, resserrage du rythme, musique, zooms et effets légers pour soutenir les réactions.',result:'Un best of plus court, plus lisible et pensé pour être regardé comme une vraie vidéo.',video:'https://www.youtube.com/watch?v=-rcfVd8Z_X0',thumb:'assets/miniature-1.png'},
{title:'Cinématique Minecraft',client:'ReviveMC',cat:'content',label:'RÉALISATION • CINÉMATIQUE',desc:'Cinématique Minecraft réalisée pour ReviveMC autour de Balls Of Steel Espace.',role:'Réalisation, écriture, colorimétrie, voix et FX',challenge:'Créer une vidéo promotionnelle qui donne une identité forte à un évènement Minecraft et transmette son ambiance rapidement.',production:'Écriture, mise en scène, réalisation des plans, voix, effets visuels et travail colorimétrique.',result:'Une cinématique courte pensée comme une bande-annonce d’évènement.',video:'https://www.youtube.com/watch?v=R_PfC2rEuYA',thumb:'assets/miniature-2.png'},
{title:'Règlement de mode de jeu',client:'ReviveMC',cat:'content',label:'RÉALISATION • EXPLICATION',desc:'Vidéo de règlement conçue pour expliquer clairement un mode de jeu ReviveMC sans perdre le rythme.',role:'Réalisation, voix, écriture, FX, colorimétrie et sound design',challenge:'Faire comprendre plusieurs règles rapidement tout en gardant une vidéo agréable et suffisamment dynamique.',production:'Écriture de l’explication, voix off, choix des images, montage, effets, sound design et colorimétrie.',result:'Une explication de règles transformée en contenu vidéo clair et travaillé.',video:'https://www.youtube.com/watch?v=SBaN_ICUA5Q',thumb:'assets/miniature-3.png'},
{title:'VOX SMP | Le récit d’une alliance brisée',client:'Codebrain',cat:'montage',label:'STORYTELLING • MONTAGE',desc:'Une vidéo storytelling qui reconstruit le récit d’une alliance brisée à partir de plusieurs POV.',role:'Voix, sound design, FX, écriture et dérush des POV',challenge:'Retrouver les bons moments dans plusieurs points de vue puis reconstruire une histoire compréhensible et progressive.',production:'Dérush multi-POV, écriture du récit, voix off, montage narratif, sound design et effets.',result:'Un évènement Minecraft raconté comme une histoire plutôt que comme une simple compilation de gameplay.',video:'https://www.youtube.com/watch?v=0WU6GrVcg60',thumb:'assets/miniature-4.png'}
];
const thumbPositionMap={0:'center 25%',3:'center 15%'};
const grid=document.querySelector('#projectGrid');function render(filter='all'){grid.innerHTML='';projects.filter(p=>filter==='all'||p.cat===filter).forEach((p,i)=>{let el=document.createElement('article');el.className='project reveal visible';const thumbPosition = thumbPositionMap[i] || 'center center';el.innerHTML=`<div class='project-thumb' style='background-image:url("${p.thumb}");background-position:${thumbPosition};'></div><div class='project-copy'><small>${p.label}</small><h3>${p.title}</h3><p>${p.desc}</p><b>Voir le projet ↗</b></div>`;el.onclick=()=>openProject(p,i);grid.appendChild(el)})}render();
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)});
function openProject(p,i){document.querySelector('#modalBody').innerHTML=`<div class='tag'>${p.client.toUpperCase()} • PROJET ${String(i+1).padStart(2,'0')}</div><h2>${p.title}</h2><p>${p.desc}</p><div class='case'><div><h4>MON RÔLE</h4><p>${p.role}</p><h4>DIFFICULTÉ</h4><p>${p.challenge}</p></div><div><h4>PRODUCTION</h4><p>${p.production}</p><h4>RÉSULTAT</h4><p>${p.result}</p></div></div><div class='actions'><a class='btn primary' href='${p.video}' target='_blank' rel='noopener'>Voir la vidéo ↗</a><button class='btn' onclick='nextProject(${i})'>Projet suivant →</button></div>`;document.querySelector('#modal').classList.add('open');document.body.style.overflow='hidden'}window.nextProject=i=>openProject(projects[(i+1)%projects.length],(i+1)%projects.length);document.querySelector('.close').onclick=()=>{document.querySelector('#modal').classList.remove('open');document.body.style.overflow=''};
document.querySelector('#theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('theme')==='light')document.body.classList.add('light');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));document.querySelector('#year').textContent=new Date().getFullYear();
const triggerAccent=(color,duration=2000)=>{const current=getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()||'#ff4d00';document.documentElement.style.setProperty('--accent',color);setTimeout(()=>document.documentElement.style.setProperty('--accent',current),duration)};
let keys='';addEventListener('keydown',e=>{keys=(keys+e.key.toLowerCase()).slice(-20);if(keys.includes('codebrain')){triggerAccent('#7cff00',1500);keys='';}if(keys.includes('arthur')){triggerAccent('#fff',1800);keys='';}});
